dspeak.ui.server=Serwer
dspeak.ui.gmodpipe=GModPipe
dspeak.ui.discord=Discord

dspeak.ui.gmodpiperequired=GMODPIPE WYMAGANY
dspeak.ui.noresponse=BRAK ODPOWIEDZI
dspeak.ui.waiting=OCZEKIWANIE...
dspeak.ui.error=BŁĄD
dspeak.ui.ok=OK
